[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; base-uri 'none'; font-src 'self' data:; form-action 'self'; frame-ancestors 'none'; frame-src app.netlify.com; img-src 'self' data:; object-src 'none'; script-src 'self' 'sha256-GUQ5ad8JK5KmEWmROf3LZd9ge94daqNvd8xy9YS1iDw='; style-src 'self';"
Permissions-Policy = "interest-cohort=()"
Referrer-Policy = "same-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
# cache-control = '''
# max-age=0,
# no-cache,
# no-store,
# must-revalidate'''

[build]
command = "npm run build"
publish = "dist"

[build.processing.html]
pretty_urls = true
